### ISSUE TITLE
ddp train mismatch error

### ISSUE THREAD

**Issue by liuyongkang1-tal** [dongrunmin/RefDiff#2]
RuntimeError: params[182] in this process with sizes [256, 256, 1, 1] appears not to match strides of the same param in process 0.

**Comment by dongrunmin** [comment]
> RuntimeError: params[182] in this process with sizes [256, 256, 1, 1] appears not to match strides of the same param in process 0.

Could give more information? For example, how did you prepare the dataset and modify the train_SECOND_X8.sh? What does your environment look like?

**Comment by dongrunmin** [comment]
> RuntimeError: params[182] in this process with sizes [256, 256, 1, 1] appears not to match strides of the same param in process 0.

Could you provide more information? For example, how did you prepare the dataset and modify the train_SECOND_X8.sh? What does your environment look like?

**Comment by liuyongkang1-tal** [comment]
I used SECOND dataset. when I trained with 1 GPU, all is right. When I trained with 2 GPUs, it did not work.

**Comment by liuyongkang1-tal** [comment]
My environment: torch=2.2 cuda 11.8

**Comment by liuyongkang1-tal** [comment]
I use your environment. It works well.
